# Generated by Django 4.2.5 on 2023-09-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('costo', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
