# Generated by Django 4.2.5 on 2023-10-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=50.25, max_digits=10),
        ),
    ]
