# Generated by Django 4.2.5 on 2023-09-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_prenda_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
                ('costo', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=20)),
                ('costo', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
    ]
