# Generated by Django 4.2.5 on 2023-10-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_prenda_imagen_url_alter_prenda_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zapato',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
