# Generated by Django 4.2.5 on 2023-09-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_accesorio_zapato'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
            ],
        ),
    ]
