# Generated by Django 4.2.5 on 2023-10-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_userregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='tipo',
        ),
    ]
